on:
  rss:
    url:
      - https://finance.yahoo.com/news/rssindex
      - https://feeds.bloomberg.com/markets/news.rss
      - https://feeds.a.dj.com/rss/RSSMarketsMain.xml
      - https://seekingalpha.com/listing/most-popular-articles.xml
      - https://www.census.gov/economic-indicators/indicator.xml
      - https://apps.bea.gov/rss/rss.xml
    config:
      every: "20 * * * *"
    parserConfig:
      headers:
        Accept:
          - 'application/rss+xml'
          - 'application/xml'
          - 'text/xml; q=0.1'
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - name: Install jq
        run: sudo apt-get install jq
      - name: Send POST Request
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          JSON_PAYLOAD=$(jq -n --arg title "$title" --arg link "$link" '{"text": $title, "link": $link}')
          curl  --connect-timeout 10 --max-time 20 --location 'https://dream-iqcavl7vwq-uc.a.run.app/discord?channel_id=1209006814922936391' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.DREAM_API_KEY }}' \
          --data "$JSON_PAYLOAD"

