on:
  rss:
    url: 
      - https://hnrss.org/newest?points=300&count=3
      - http://rss.cnn.com/rss/cnn_topstories.rss
      - http://rss.cnn.com/rss/cnn_latest.rss
    config:
      limit: 15
      # every: */5 * * * * # every 10 mins
      # debug: true
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - name: Send POST Request
        run: |
          curl -X POST https://example.com/api/data \ 
          -H "Content-Type: application/json" \ 
          -d '{"param1":"value1", "param2":"value2"}'
