on:
  reddit:
    url:
      - https://www.reddit.com/r/Showerthoughts/
      - https://www.reddit.com/r/quotes/
    # config:
    #   limit: 15
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.reddit.outputs.title}}
          link: ${{on.reddit.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
      - name: Install jq
        run: sudo apt-get install jq
      - name: Send POST Request
        env:
          title: ${{on.reddit.outputs.title}}
          link: ${{on.reddit.outputs.link}}
        run: |
          JSON_PAYLOAD=$(jq -n --arg title "$title" --arg link "$link" '{"text": $title, "link": $link}')
          curl --location 'https://dream-iqcavl7vwq-uc.a.run.app/discord?channel_id=1213724336129581067' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.DREAM_API_KEY }}' \
          --data "$JSON_PAYLOAD"

