on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.X_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.X_CONSUMER_SECRET }}
      access_token: ${{ secrets.X_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
    params:
      screen_name: theowenyoung
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          text: ${{on.twitter.outputs.text}}
          # contentSnippet: ${{on.rss.outputs.contentSnippet}}
          # link: ${{on.rss.outputs.link}}
        run: |
          echo text: $text
          # echo contentSnippet: $contentSnippet
          # echo link: $link
      # - name: Install jq
      #   run: sudo apt-get install jq
      # - name: Send POST Request
      #   env:
      #     title: ${{on.rss.outputs.title}}
      #     contentSnippet: ${{on.rss.outputs.contentSnippet}}
      #     link: ${{on.rss.outputs.link}}
      #   run: |
      #     JSON_PAYLOAD=$(jq -n --arg title "$title" --arg link "$link" '{"text": $title, "link": $link}')
      #     curl --location 'https://dream-s47zheng.k8s.csclub.cloud/discord?channel_id=1148501160261591071' \
      #     --header 'Content-Type: application/json' \
      #     --header 'Authorization: Bearer ${{ secrets.DREAM_API_KEY }}' \
      #     --data "$JSON_PAYLOAD"

