on:
  twitter:
    api: user_timeline
    auth:
      consumer_key: ${{ secrets.X_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.X_CONSUMER_SECRET }}
      access_token: ${{ secrets.X_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
    params:
      screen_name: houzz
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          text: ${{ on.twitter.outputs.full_text }}
        run: |
          echo text: $text
      - name: Send POST Request
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          curl --location 'https://dream-s47zheng.k8s.csclub.cloud/discord' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.DREAM_API_KEY }}' \
          --data '{
            "text": "'"$text"'",
            "link": ""
          }'

